### ISSUE TITLE
Test :  Test all Vision models with small MNIST

### ISSUE THREAD

**Issue by arita37** [arita37/mlmodels#112]

**Comment by avijit9** [comment]
In `benchmark.py` do we need to train the models? or just the test code? because test folder is .gitignored, we don't have models pretrained on MNIST.

**Comment by arita37** [comment]
Please train with epochs=2
(so small size mnist is ok)

1) Check this one

torchhub.py/test()

2) you need to create

```
def benchmark_vision(   json_file_list) :

  for jsonf in json_file_list
```

**Comment by avijit9** [comment]
And the evaluation code should be in `fit_metrics` in `torchhub.py`?

**Comment by avijit9** [comment]
Also, while using `util.metrics_evaluate` I am getting the following error: 

`*** TypeError: __call__() missing 1 required positional argument: 'y_true'`

Did it work for you?

**Comment by arita37** [comment]
fit-metrics: training metrics
metrics() : out of sample.

Yes, please check util.metrics evaluate

( just committed)

**Comment by avijit9** [comment]
I am getting the same error while using the `util.metrics_evaluate`

**Comment by arita37** [comment]
Can you the one in

benchmark.py

This one is working

**Comment by avijit9** [comment]
Hi, 

Can you please clarify what goes in fit-metrics and metrics you mentioned above?

**Comment by arita37** [comment]
Accuracy metric is fine....
Check mnist related model

**Comment by arita37** [comment]
![image](https://user-images.githubusercontent.com/18707623/78748493-22e2a700-79a7-11ea-90e5-436fbdbb954c.png)

**Comment by avijit9** [comment]
<img width="643" alt="Screenshot 2020-04-08 at 19 17 20" src="https://user-images.githubusercontent.com/22516722/78791568-b0d18880-79cd-11ea-8e30-a9dd4f776e3d.png">
Tests passed.

**Comment by arita37** [comment]
@avijit9  : Number of classes output should 9 (<> from standard model...)
