### ISSUE TITLE
Add autokeras

### ISSUE THREAD

**Issue by arita37** [arita37/mlmodels#135]
Add in
model_keras/autokeras.py

https://autokeras.com/tutorial/overview/

**Comment by Abhi001vj** [comment]
I will add text classification models

**Comment by arita37** [comment]
Text classifications are useful.
API looks easy to use.

**Comment by Abhi001vj** [comment]
![image](https://user-images.githubusercontent.com/9322388/78895067-ce652780-7a8b-11ea-88a3-48af0ae13ea0.png)
error while pushing from gitpod

**Comment by arita37** [comment]
Your success run 

please use
from mlmodels.util import path_norm

Not this one
sys.path.apped('../../')


https://github.com/arita37/mlmodels/blob/dev/.github/workflows/test_specific_model.yml

**Comment by arita37** [comment]
![image](https://user-images.githubusercontent.com/18707623/78896494-85bd6680-7aab-11ea-8123-6dc923580cdc.png)
