### ISSUE TITLE
Add : Vision Progressive GAN

### ISSUE THREAD

**Issue by arita37** [arita37/mlmodels#138]
This one using torchhub.py

https://pytorch.org/hub/facebookresearch_pytorch-gan-zoo_pgan/

https://colab.research.google.com/github/pytorch/pytorch.github.io/blob/master/assets/hub/facebookresearch_pytorch-gan-zoo_pgan.ipynb

torchhub.py code
https://colab.research.google.com/github/pytorch/pytorch.github.io/blob/master/assets/hub/facebookresearch_pytorch-gan-zoo_pgan.ipynb

**Comment by souravsingh** [comment]
Working on this.
