### ISSUE TITLE
CLI : Clean up examples in Readme CLI and test CLI

### ISSUE THREAD

**Issue by arita37** [arita37/mlmodels#215]
Goal is : 
   Clean up/Format this readme and make it easy to use
   https://github.com/arita37/mlmodels/blob/dev/README_usage_CLI.md

   Add more examples of CLI usage with correct Markdown formatting.
   

   Test in Google Colab the CLI usage :       https://colab.research.google.com/drive/1qkC7enImfhTWA8YXMXZDOKJ2XKaARMUW#scrollTo=ckk9XJguZwRB

CLI code :
https://github.com/arita37/mlmodels/blob/dev/setup.py#L119-L124

**Comment by pushkalkatara** [comment]
Hi @arita37 I would like to work on the issue.

**Comment by pushkalkatara** [comment]
Breaking down into several small parts, would add iteratively:
- [x] Removing displaying __init__ files.
