### ISSUE TITLE
Jupyter : Test on KMNIST  using Vision models

### ISSUE THREAD

**Issue by arita37** [arita37/mlmodels#236]
https://github.com/arita37/mlmodels/blob/dev/mlmodels/example/README_usage.md#resnet18-trained-on-fashion-mnist-colab

https://colab.research.google.com/gist/iyaja/fe102ae34312e48e637edd804a450207/kmnist.ipynb

https://pytorch.org/docs/stable/torchvision/datasets.html#kmnist

**Comment by souravsingh** [comment]
I am interested in working on this.

**Comment by arita37** [comment]
Ok, please go ahead.
There is some notebooks ready.
