### ISSUE TITLE
Manual installation setup

### ISSUE THREAD

**Issue by pushkalkatara** [arita37/mlmodels#243]
Currently to manually install ml_models for development, the README.md instructions are missing one step:

```
python setup.py install
```

**Comment by arita37** [comment]
https://github.com/arita37/mlmodels/blob/dev/README_addmodel.md#manual-installation

**Comment by pushkalkatara** [comment]
https://github.com/arita37/mlmodels#b-manual-install-as-editable-package-in-linux
