### ISSUE TITLE
Error in running ResNet18 trained on Fashion MNIST in Colab

### ISSUE THREAD

**Issue by hassanms** [arita37/mlmodels#261]
I am trying this ResNet18 example in Colab:

https://github.com/arita37/mlmodels/blob/dev/mlmodels/example/README_usage.md#resnet18-trained-on-fashion-mnist-colab

Upon executing the last block of the notebook, I get this error:

> {'model_uri': 'model_tch.torchhub.py', 'repo_uri': 'pytorch/vision', 'model': 'resnet18', 'num_classes': 10, 'pretrained': 0, '_comment': '0: False, 1: True', 'num_layers': 5, 'size': 6, 'size_layer': 128, 'output_size': 6, 'timestep': 4, 'epoch': 2} {'dataset': 'FashionMNIST', 'data_path': 'dataset/vision/', 'train_batch_size': 100, 'test_batch_size': 10} {'distributed': 'mpi', 'max_batch_sample': 100, 'epochs': 10, 'learning_rate': 0.001} {'checkpointdir': 'ztest/model_tch/torchhub/restnet18/checkpoints/', 'path': 'ztest/model_tch/torchhub/restnet18/'}
Downloading: "https://github.com/pytorch/vision/archive/master.zip" to /root/.cache/torch/hub/master.zip
---------------------------------------------------------------------------

> KeyError                                  Traceback (most recent call last)
> <ipython-input-9-2bae58f95f5a> in <module>()
>      22 
>      23 #### Fit
> ---> 24 model, session = module.fit(model, data_pars, compute_pars, out_pars)           #### fit model
>      25 metrics_val    = module.fit_metrics(model, data_pars, compute_pars, out_pars)   #### Check fit metrics
>      26 print(metrics_val)
> 
> 2 frames
> /content/mlmodels/mlmodels/model_tch/torchhub.py in get_dataset_torch(data_pars)
>     135 def get_dataset_torch(data_pars):
>     136 
> --> 137     if  data_pars["transform"]  :
>     138        transform = load_function(  data_pars.get("preprocess_module", "mlmodels.preprocess.image"), 
>     139                                    data_pars.get("transform", "torch_transform_mnist" ))
> 
> KeyError: 'transform'

**Comment by arita37** [comment]
Please use correct JSON : 
https://github.com/arita37/mlmodels/blob/dev/mlmodels/model_tch/torchhub_cnn_list.json
