### ISSUE TITLE
Type error : from gluonts.model.deepar import DeepAREstimator

### ISSUE THREAD

**Issue by hafsabukhary** [arita37/mlmodels#308]
I am running ml model on goole colab, I have set up according to this notebook 
https://colab.research.google.com/drive/1oRGEUDisR2lGrtbkKNKoN6_ooBmuCM3j?hl=en#scrollTo=rTf9qA5k4Q_0

when I try to use DeepAREstimator with the line
`from gluonts.model.deepar import DeepAREstimator`

I get following error
```
TypeError                                 Traceback (most recent call last)
<ipython-input-11-9f6c51315a4e> in <module>()
----> 1 from gluonts.model.deepar import DeepAREstimator
      2 from gluonts.distribution.neg_binomial import NegativeBinomialOutput
      3 from gluonts.trainer import Trainer

6 frames
/usr/local/lib/python3.6/dist-packages/gluonts/model/deepar/__init__.py in <module>()
     13 
     14 # Relative imports
---> 15 from ._estimator import DeepAREstimator
     16 
     17 __all__ = ["DeepAREstimator"]

/usr/local/lib/python3.6/dist-packages/gluonts/model/deepar/_estimator.py in <module>()
     22 from gluonts.core.component import DType, validated
     23 from gluonts.dataset.field_names import FieldName
---> 24 from gluonts.distribution import DistributionOutput, StudentTOutput
     25 from gluonts.model.estimator import GluonEstimator
     26 from gluonts.model.predictor import Predictor, RepresentableBlockPredictor

/usr/local/lib/python3.6/dist-packages/gluonts/distribution/__init__.py in <module>()
     13 
     14 # Relative imports
---> 15 from . import bijection
     16 from .binned import Binned, BinnedOutput
     17 from .box_cox_tranform import (

/usr/local/lib/python3.6/dist-packages/gluonts/distribution/bijection.py in <module>()
     26 
     27 
---> 28 class Bijection:
     29     """
     30     A bijective transformation.

/usr/local/lib/python3.6/dist-packages/gluonts/distribution/bijection.py in Bijection()
     34     """
     35 
---> 36     @validated()
     37     def __init__(self):
     38         pass

/usr/local/lib/python3.6/dist-packages/gluonts/core/component.py in validator(init)
    396                 model_name=f"{init_clsnme}Model",
    397                 __config__=BaseValidatedInitializerModel.Config,
--> 398                 **init_fields,
    399             )
    400         else:

/usr/local/lib/python3.6/dist-packages/pydantic/main.cpython-36m-x86_64-linux-gnu.so in pydantic.main.create_model()

TypeError: create_model() takes exactly 1 positional argument (0 given)
```
![image](https://user-images.githubusercontent.com/16378547/82110426-f36a4b80-9757-11ea-8b02-8fb90eaaa92f.png)

**Comment by arita37** [comment]
Related to some packages issues :

 lostella commented 27 days ago

@joaoTray would constraining the pydantic requirement to <=1.4 be a solution for you? Or do you strictly require 1.5?
@joaoTray
Author
joaoTray commented 27 days ago
Hi,

The 1.4 will be fine.
I will use this version for now.

Many thanks,
Joao

**Comment by arita37** [comment]
Solution :  add this (and re-start the runtime)

  !pip install pydantic==1.4  --force

**Comment by hafsabukhary** [comment]
The issue is fixed . thank you

**Comment by arita37** [comment]
Does the notebook works now ?

**Comment by hafsabukhary** [comment]
No. Found other issues. 
The function 

`pandas_to_gluonts_multiseries(df_timeseries, df_dynamic, df_static, pars=None) :` 
has pars equal to None.
And then we call it using this line
`train_ds, test_ds = pandas_to_gluonts_multiseries(df_timeseries, df_dynamic, df_static, pars=None) 
`
Which produces following error
![image](https://user-images.githubusercontent.com/16378547/82155308-78a34c80-988d-11ea-995a-7fd00b012aaa.png)
I have tried few workarounds but lead to other errors. 
Why are we getting values from a NONE Object ?
