### ISSUE TITLE
Issue at Dataset generation stage

### ISSUE THREAD

**Issue by engrzaky** [arita37/mlmodels#311]
I am having the following error at Dataset generation stage.

`KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: ('item_id', 'dept_id', 'cat_id', 'store_id', 'state_id')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
2 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2646                 return self._engine.get_loc(key)
   2647             except KeyError:
-> 2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2649         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2650         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: ('item_id', 'dept_id', 'cat_id', 'store_id', 'state_id')`

**Comment by arita37** [comment]
Screenshot + Code which produce the error, pls

**Comment by engrzaky** [comment]
![image](https://user-images.githubusercontent.com/28868513/82111999-733ce980-9749-11ea-80a9-92929b2a4ddd.png)

**Comment by engrzaky** [comment]
The error actually occurs in base.py file. Should I share that?

**Comment by arita37** [comment]
Csv file column names please.
Just follow error message

**Comment by engrzaky** [comment]
The problem is solved as below. But a new problem arise (see the screenshot below)
`#df_static     = sales_train_val["item_id","dept_id","cat_id","store_id","state_id"]
df_static     = sales_train_val[["item_id","dept_id","cat_id","store_id","state_id"]] # This works but another problem arises (Zahoor)`

**Comment by engrzaky** [comment]
![image](https://user-images.githubusercontent.com/28868513/82122105-d488ab00-9791-11ea-8247-7b4fa2a9c249.png)

**Comment by engrzaky** [comment]
The column names are fine
