### ISSUE TITLE
Add Match ZOO NLP models

### ISSUE THREAD

**Issue by arita37** [arita37/mlmodels#74]
https://github.com/NTMC-Community/MatchZoo

**Comment by arita37** [comment]
do we need a strategy to take individual MatchZoo models like DRMMm Match Pyramid and integrate each individually according to mlmodels pipeline?

or do we need to expose MatchZoo library as a dependency in mlmodels and expose all models

**Comment by arita37** [comment]
MatchZoo is a dependency, fully exposed

**Comment by pushkalkatara** [comment]
hence, we need to follow the template and expose matchzoo for our pipeline.

**Comment by arita37** [comment]
Full exposure of matchzoo like torch hub.py

**Comment by pushkalkatara** [comment]
matchzoo is recently available in torch also, do we need to add the torch version or the tensorflow version?

**Comment by arita37** [comment]
Pytorch version only

**Comment by pushkalkatara** [comment]
there are two tasks in matchzoo using several models, the two tasks are - 1. ranking 2. classification.

Which one needs to be integrated?

**Comment by arita37** [comment]
@pushkalkatara :
Thx for PR !

  You also need to add in (for PR auto-testing)
   https://github.com/arita37/mlmodels/blob/dev/pullrequest.json
   https://github.com/arita37/mlmodels/actions?query=workflow%3Atest_pullrequest


Next step, will be to customize the task (outside of ranking).

**Comment by arita37** [comment]
Classification added :
https://github.com/arita37/mlmodels/blob/ad7cccacf5e216bb6101589f85c6874cf0af8a3e/mlmodels/model_tch/matchzoo_models.py#L82-L89

**Comment by arita37** [comment]
[4/7/2020 7:49:58 PM]  Yes, as different model use different ranking metrics, we might have to extend conditions for all models seperately.

[4/7/2020 7:50:35 PM]   also, different models have different preprocessing scripts. so if conditions for that also would increase.

[4/7/2020 8:58:37 PM]   Your idea of using dict as MODEL_LIST ={} is very Good
