### ISSUE TITLE
Add Facebook Prophet example

### ISSUE THREAD

**Issue by arita37** [arita37/mlmodels#85]
Implement and test phrophet estimator time series

https://github.com/arita37/mlmodels/blob/dev/README_addmodel.md

**Comment by arita37** [comment]
Here :
https://github.com/arita37/mlmodels/blob/metric/mlmodels/model_gluon/gluon_prophet.py

**Comment by SaifullahKatpar** [comment]
On running `gluon_prophet.py` on Gitpod, it gives following error:

![gluon_prophet_error](https://user-images.githubusercontent.com/20139234/78776983-9c4dab80-794d-11ea-86f6-7d3a357aec63.PNG)

Should I add the code for train if it's not there already?

**Comment by arita37** [comment]
Please add the code of train if needed, and make it work

**Comment by arita37** [comment]
If you google a bit....
https://discuss.mxnet.io/t/fbprophet-with-gluonts/4713
